### ISSUE TITLE
A15 15.4.1

### ISSUE THREAD

**Issue by GiftedK** [opa334/TrollNonce#2]
Hello, it did not seem to work on my iPhone 13 Pro max using TrollStore 2. So please update to 15.4.1 as I need to featurerestore again to try and fix my FaceID. Also, it would be helpful if you can fix the paste issue as it wont paste from the clipboard to the nonce field, so we'll have to enter the generator manually.

**Comment by opa334** [comment]
not possible until fugu15 is out
