### ISSUE TITLE
TrollNonce not working

### ISSUE THREAD

**Issue by igorbretas** [opa334/TrollNonce#7]
I have an iPhone XR A12, it was on 15.4 so i used TrollNonce to upgrade to 15.4.1 but i checked the preserve data option on futurerestore and it went well. But i need it completly restored and i need to use TrollNonce again but after hitting set it doesn´t show the Sucess pop-up and don´t change the nonce even after restarting. Both TrollStore and TrollNonce are updated.
<img width="414" alt="Imagem PNG" src="https://user-images.githubusercontent.com/34289964/197243823-2e6a5402-b4fd-49c2-9199-00584a51c073.png">

**Comment by opa334** [comment]
TrollNonce does not support 15.4.1. You can factory reset in settings.

**Comment by igorbretas** [comment]
Sorry to ask, but factory reset won´t upgrade the iOS?

**Comment by opa334** [comment]
it won't
